# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "devel" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "devel" ]
 # schedule:
 #   - cron: '44 1 * * 3'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan repository with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: 'sarif'  
          limit-severities-for-sarif: true #By default SARIF format enforces output of all vulnerabilities. To override this behavior set this parameter to true
          severity: 'HIGH,CRITICAL'
          output: trivy-results.sarif
          skip-dirs: website 
        continue-on-error: true  # still upload SARIF even if vulnerabilities exist

      - name: Debug SARIF
        run: |
            head -n 20 trivy-results.sarif
            jq .version trivy-results.sarif   
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
